"""empty message

Revision ID: 715fda9d5211
Revises: 48bef398534a
Create Date: 2022-10-14 16:43:49.422233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715fda9d5211'
down_revision = '48bef398534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('matches', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('teams', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('teams_name_key', 'teams', type_='unique')
    op.drop_column('teams', 'id')
    op.add_column('users', sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_time')
    op.add_column('teams', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('teams_name_key', 'teams', ['name'])
    op.drop_column('teams', 'time_created')
    op.drop_column('matches', 'time_created')
    op.drop_column('bets', 'created_time')
    # ### end Alembic commands ###
