"""clases con una relacion Bet-Match

Revision ID: 82abc53dd963
Revises: 013700a9977d
Create Date: 2022-10-14 11:09:58.800723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82abc53dd963'
down_revision = '013700a9977d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('match_code', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bets', 'matches', ['match_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bets', type_='foreignkey')
    op.drop_column('bets', 'match_code')
    # ### end Alembic commands ###
