"""empty message

Revision ID: 906a34c81f9e
Revises: 7050d81d53b1
Create Date: 2022-10-18 08:26:07.053691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906a34c81f9e'
down_revision = '7050d81d53b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
