"""empty message

Revision ID: 17f3df8f0072
Revises: 705d99fc2bcc
Create Date: 2022-10-14 11:01:58.279466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f3df8f0072'
down_revision = '705d99fc2bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bets_id_user_fkey', 'bets', type_='foreignkey')
    op.drop_constraint('bets_match_code_fkey', 'bets', type_='foreignkey')
    op.drop_column('bets', 'match_code')
    op.drop_column('bets', 'id_user')
    op.drop_constraint('matches_local_fkey', 'matches', type_='foreignkey')
    op.drop_constraint('matches_visit_fkey', 'matches', type_='foreignkey')
    op.drop_column('matches', 'local')
    op.drop_column('matches', 'visit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('visit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('local', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('matches_visit_fkey', 'matches', 'teams', ['visit'], ['name'])
    op.create_foreign_key('matches_local_fkey', 'matches', 'teams', ['local'], ['name'])
    op.add_column('bets', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bets', sa.Column('match_code', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('bets_match_code_fkey', 'bets', 'matches', ['match_code'], ['code'])
    op.create_foreign_key('bets_id_user_fkey', 'bets', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###
