"""Initial database

Revision ID: 4881c0557c82
Revises: 
Create Date: 2022-10-13 11:33:57.929734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4881c0557c82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_table('transacciones')
    op.drop_table('teams')
    # ### end Alembic commands ###
