"""agregado la clase local

Revision ID: e098c593d08c
Revises: 82abc53dd963
Create Date: 2022-10-14 11:14:35.377935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e098c593d08c'
down_revision = '82abc53dd963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'matches', 'teams', ['local'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    # ### end Alembic commands ###
